remote_theme: ddc-java/ddc-day-book
repository_link:
  enabled: false
page_navigator:
  enabled: true
titles_from_headings:
  enabled: false
prev_next_navigation:
- bottom

# TODO Modify the contents below for the specific project. NOTE THE INDENTATION!

title: "Delta Draft"
description: "Dominate your draft with Delta Draft! Using the power of baseball-reference, 
advanced stats, and custom queries, change up your draft strategy. Don't just draft, Delta Draft"
author:
  name: "Travis Hollins"

# Do not change the following line.
  copyright: true
